name: Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Resume repo
        uses: actions/checkout@v3
        with:
          repository: fmillone/react-web-resume

      - name: Checkout data repo
        uses: actions/checkout@v3
        with:
          repository: fmillone/web-resume-data
          path: data
          token: ${{secrets.PAT_REPOS}}
        env: 
          PAT_REPOS: ${{secrets.PAT_REPOS}}

      # Runs a single command using the runners shell
      - name: copy files to repo
        run: |
          cp data/profile_photo.jpg ./src/images/
          cp data/resume-data.json ./src/data/
          cp data/public/* ./public/
      
      #- name: Setup Node.js environment
      #  uses: actions/setup-node@v3.2.0

      - name: npm install
        run: npm install
        
      - name: Deploy with gh-pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REACT_APP_TITLE: "Francisco Millone"
          REACT_APP_ANALYTICS_KEY: ${{ secrets.G_ANALYTICS_KEY }}
        
